# Generated by Django 4.1.3 on 2022-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_id', models.PositiveIntegerField()),
                ('Project_Title', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=15)),
                ('Project_priority', models.CharField(max_length=50)),
                ('Client', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField()),
                ('Project_start_Date', models.CharField(max_length=30)),
                ('Project_End_Date', models.CharField(max_length=30)),
                ('Team', models.CharField(max_length=50)),
                ('Work_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'completed'), ('Running', 'Running'), ('pending', 'pending'), ('Not started', 'Not started'), ('Cancelled', 'cancelled')], max_length=30)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
