# Generated by Django 4.1.3 on 2022-11-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=15)),
                ('Department', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Contact_Number', models.PositiveIntegerField()),
                ('Adrees_Field_1', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
