# Generated by Django 4.1.3 on 2022-11-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Leave_Type', models.CharField(max_length=30)),
                ('Leave_from', models.CharField(max_length=15)),
                ('Leave_To', models.CharField(max_length=50)),
                ('No_of_Days', models.PositiveIntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Reason', models.CharField(max_length=100)),
            ],
        ),
    ]
