# Generated by Django 4.1.3 on 2022-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday_Name', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=15)),
                ('Shift', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=50)),
            ],
        ),
    ]
